### ISSUE TITLE
Commande /fk rules AllowBlock ne fonctionnant pas totalement

### ISSUE THREAD

**Issue by DarkBoow** [Etrenak/FallenKingdom#10]
Salut, dans la version 2.16.1 du plugin, sur un serveur minecraft en 1.8.7, la commande /fk rules AllowBlock ne fonctionne pas pour l'option d'ajouter le bloc que l'on tient en main dans les blocs autorisés.

**Comment by Etrenak** [comment]
Bonjour @DarkBoow, il me faudrait le contenu des logs de ton serveur à ce moment là s'il te plaît.
