### ISSUE TITLE
Permissions d'utiliser les commandes pour d'autres joueurs

### ISSUE THREAD

**Issue by AYoloss** [Etrenak/FallenKingdom#25]
Bonjour,

J'ai un petit soucis concernant le plugin : les autres participant de la partie ne peuvent pas utiliser les commandes comme /fk team chestsRoom show <sec>.
C'est une des commandes utiles en jeu et je me retrouve à être le seul à pouvoir les utiliser, étant le seul OP du serveur. Y a t il un moyen de donner accès à ces commandes aux autres joueurs sans les OP ? (afin d'éviter les abus et/ou triches)

Merci !

**Comment by syldium** [comment]
Bonjour,
La commande `/fk` de base est définie avec une permission qui n'est effectivement pas définie pour les joueurs par défaut. Avec un plugin de permissions comme LuckPerms, définir `fallenkingdom.commands` à *true* permet de rendre la commande accessible.
`/lp group default permission set fallenkingdom.commands`

**Comment by syldium** [comment]
Corrigé en 2.21.2
