### ISSUE TITLE
chestsRoom show command don't work

### ISSUE THREAD

**Issue by Synol14** [Etrenak/FallenKingdom#27]
I can't use `/fk team chestsRoom show` command and this command returns an error.
I'm in a team and the game has been started.
![image](https://user-images.githubusercontent.com/62247993/205439097-801214c0-5a1b-44db-9a1a-282e1f223f3c.png)

**Comment by syldium** [comment]
This command requires an additional argument, the display duration. If you want to see the edges of the chest room for one second for instance, use the `/fk team chestsRoom show 1` command.

**Comment by Synol14** [comment]
Ok I'm sorry, it's work well. Thank you.
