### ISSUE TITLE
Scoreboard and hotbar glitch

### ISSUE THREAD

**Issue by Jafff7** [Etrenak/FallenKingdom#28]
Hello,

Je viens d'installer le plugin et après une revue des règles, j'ai remarquer que le scoreboard était devenu blanc :
![2023-02-04_14 49 24](https://user-images.githubusercontent.com/124445297/216771227-6ba82952-4df1-4cb1-a7ce-03a05b5d34ea.png)
![2023-02-04_14 49 25](https://user-images.githubusercontent.com/124445297/216771228-fbafc0d1-6a00-4f46-bf26-4774884e5e08.png)

A chaque fois que change d'emplacement sur ma hotbar, il passe de "normal" à la version "code"!
C'est juste l'apparence, ça n'affecte pas le reste du plugin, mais je ne sais pas si le problème viens de moi, du server ou du plugin!

Merci
-J

**Comment by syldium** [comment]
Il s'agit du mode édition du scoreboard. Pour en sortir, vous pouvez utiliser la commande `/fk scoreboard leaveEdit`

**Comment by Jafff7** [comment]
Ok!!
Merci beaucoup, c'était donc moi !

bon week-end!
-J
