### ISSUE TITLE
Impossible de rejoindre le serveur.

### ISSUE THREAD

**Issue by thomas-rx** [Etrenak/FallenKingdom#4]
Bonjour, votre plugin a l'air formidable mais malheureusement après installation je n'arrive pas à me connecter au serveur, il me dit que ma version de Java (qui est la V8) n'est pas compatible avec le plugin... 
Pourtant j'ai la Version 8, mon jeu se lance en version 8. 
Je ne sais plus quoi faire..

**Comment by Blendman974** [comment]
Y'a t'il des messages d'erreur dans les logs serveur ?
Notez d'ailleurs qu'il faut que le serveur ai la version 8 de java (et non pas le client/jeu)

**Comment by thomas-rx** [comment]
J'ai réussi à résoudre le problème, j'ai galéré mais réussi, donc ceux qui ont un serveur hébergé sur une arch linux, il faut sectionner la version de java 8, jdk 11 ne fonctionne pas.

**Comment by Etrenak** [comment]
Tant mieux ! Désolé pour cette réponse tardive, pour recevoir de l'aide plus rapidement -> https://discord.gg/SmAAFxh
