### ISSUE TITLE
Bug avec le FK Config

### ISSUE THREAD

**Issue by HysideL** [Etrenak/FallenKingdom#5]
Le FK config ne marche pas quand je me connecte alors que les identifiants sont bons.
Voici l erreur:

ConnectException >> Connection timed out: connect

-> java.net.DualStackPlainSocketImpl.connect0(Native Method)
-> java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
-> java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
-> java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
-> java.net.AbstractPlainSocketImpl.connect(Unknown Source)
-> java.net.PlainSocketImpl.connect(Unknown Source)
-> java.net.SocksSocketImpl.connect(Unknown Source)
-> java.net.Socket.connect(Unknown Source)
-> java.net.Socket.connect(Unknown Source)
-> java.net.Socket.<init>(Unknown Source)
-> java.net.Socket.<init>(Unknown Source)
-> fr.devsylone.fkapp.connection.Connection.connect(Connection.java:33)
-> fr.devsylone.fkapp.graphic.listeners.connect.ConnectButtonListener.actionPerformed(ConnectButtonListener.java:35)
-> javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
-> javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
-> javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
-> javax.swing.DefaultButtonModel.setPressed(Unknown Source)
-> javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
-> java.awt.Component.processMouseEvent(Unknown Source)
-> javax.swing.JComponent.processMouseEvent(Unknown Source)
-> java.awt.Component.processEvent(Unknown Source)
-> java.awt.Container.processEvent(Unknown Source)
-> java.awt.Component.dispatchEventImpl(Unknown Source)
-> java.awt.Container.dispatchEventImpl(Unknown Source)
-> java.awt.Component.dispatchEvent(Unknown Source)
-> java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
-> java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
-> java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
-> java.awt.Container.dispatchEventImpl(Unknown Source)
-> java.awt.Window.dispatchEventImpl(Unknown Source)
-> java.awt.Component.dispatchEvent(Unknown Source)
-> java.awt.EventQueue.dispatchEventImpl(Unknown Source)
-> java.awt.EventQueue.access$500(Unknown Source)
-> java.awt.EventQueue$3.run(Unknown Source)
-> java.awt.EventQueue$3.run(Unknown Source)
-> java.security.AccessController.doPrivileged(Native Method)
-> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
-> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
-> java.awt.EventQueue$4.run(Unknown Source)
-> java.awt.EventQueue$4.run(Unknown Source)
-> java.security.AccessController.doPrivileged(Native Method)
-> java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
-> java.awt.EventQueue.dispatchEvent(Unknown Source)
-> java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
-> java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
-> java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
-> java.awt.EventDispatchThread.pumpEvents(Unknown Source)
-> java.awt.EventDispatchThread.pumpEvents(Unknown Source)
-> java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Blendman974** [comment]
Salut, vérifie que le port config (tpc/50000) est ouvert coté serveur.

**Comment by Etrenak** [comment]
Aucune réponse de l'auteur, je clos.
