### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by TheFox580** [Etrenak/FallenKingdom#8]
![Bug](https://user-images.githubusercontent.com/44817153/65379060-67844a80-dcc2-11e9-9c59-667feac18cca.jpg)

Bah voila quoi...

**Comment by LukaMrt** [comment]
@TheFox580 est-ce que tu as cette apparence quand tu edit le scoreboard ?
Normalement elle permet de montrer comment faire pour changer les lignes pour afficher les différentes infos

**Comment by Etrenak** [comment]
Bonjour @TheFox580,
Il suffit de quitter la modification du scoreboard via la commande /fk scoreboard leaveedit
